### ISSUE TITLE
Add HTMetadata as submodule and call from Makefile

### ISSUE THREAD

**Issue by bmschmidt** [Bookworm-project/Hathitrust-Bookworm#1]
Not the only way to do it, but perhaps the easiest way for this repo to create the needed `jsoncatalog.txt` and `field_descriptions.json` is simply to clone the [HT-metadata repo](https://github.com/Bookworm-project/HTMetadata-Bookworm), `$(MAKE) -C jsoncatalog.txt` inside that directory, and then pull them back out wherever they need to do.

In reality, we'll probably just be copying the file over in any case for this round.

**Comment by organisciak** [comment]
Great. Already had the first part prepped, just updated the Makefile with c00ae20. Would a symbolic link from HTMetadata-Bookworm/realjsoncatalog.txt to BookwormDB/files/metadata/jsoncatalog.txt cause any problems down the line? I don't expect to, but don't want to test it while my systems are crunching away.

**Comment by bmschmidt** [comment]
No, I use symbolic links for this all the time. I think that one you posted needs a relative location, though (../../HTMetadata-Bookworm/realjsoncatalog.txt, or something like that.)
